// <auto-generated />
using Customer.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customer.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Customer")
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Customer.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Name = "Customer 1"
                        },
                        new
                        {
                            ClientId = 2,
                            Name = "Customer 2"
                        },
                        new
                        {
                            ClientId = 3,
                            Name = "Customer 3"
                        },
                        new
                        {
                            ClientId = 4,
                            Name = "Customer 4"
                        },
                        new
                        {
                            ClientId = 5,
                            Name = "Customer 5"
                        },
                        new
                        {
                            ClientId = 6,
                            Name = "Customer 6"
                        },
                        new
                        {
                            ClientId = 7,
                            Name = "Customer 7"
                        },
                        new
                        {
                            ClientId = 8,
                            Name = "Customer 8"
                        },
                        new
                        {
                            ClientId = 9,
                            Name = "Customer 9"
                        },
                        new
                        {
                            ClientId = 10,
                            Name = "Customer 10"
                        },
                        new
                        {
                            ClientId = 11,
                            Name = "Customer 11"
                        },
                        new
                        {
                            ClientId = 12,
                            Name = "Customer 12"
                        },
                        new
                        {
                            ClientId = 13,
                            Name = "Customer 13"
                        },
                        new
                        {
                            ClientId = 14,
                            Name = "Customer 14"
                        },
                        new
                        {
                            ClientId = 15,
                            Name = "Customer 15"
                        },
                        new
                        {
                            ClientId = 16,
                            Name = "Customer 16"
                        },
                        new
                        {
                            ClientId = 17,
                            Name = "Customer 17"
                        },
                        new
                        {
                            ClientId = 18,
                            Name = "Customer 18"
                        },
                        new
                        {
                            ClientId = 19,
                            Name = "Customer 19"
                        },
                        new
                        {
                            ClientId = 20,
                            Name = "Customer 20"
                        },
                        new
                        {
                            ClientId = 21,
                            Name = "Customer 21"
                        },
                        new
                        {
                            ClientId = 22,
                            Name = "Customer 22"
                        },
                        new
                        {
                            ClientId = 23,
                            Name = "Customer 23"
                        },
                        new
                        {
                            ClientId = 24,
                            Name = "Customer 24"
                        },
                        new
                        {
                            ClientId = 25,
                            Name = "Customer 25"
                        },
                        new
                        {
                            ClientId = 26,
                            Name = "Customer 26"
                        },
                        new
                        {
                            ClientId = 27,
                            Name = "Customer 27"
                        },
                        new
                        {
                            ClientId = 28,
                            Name = "Customer 28"
                        },
                        new
                        {
                            ClientId = 29,
                            Name = "Customer 29"
                        },
                        new
                        {
                            ClientId = 30,
                            Name = "Customer 30"
                        },
                        new
                        {
                            ClientId = 31,
                            Name = "Customer 31"
                        },
                        new
                        {
                            ClientId = 32,
                            Name = "Customer 32"
                        },
                        new
                        {
                            ClientId = 33,
                            Name = "Customer 33"
                        },
                        new
                        {
                            ClientId = 34,
                            Name = "Customer 34"
                        },
                        new
                        {
                            ClientId = 35,
                            Name = "Customer 35"
                        },
                        new
                        {
                            ClientId = 36,
                            Name = "Customer 36"
                        },
                        new
                        {
                            ClientId = 37,
                            Name = "Customer 37"
                        },
                        new
                        {
                            ClientId = 38,
                            Name = "Customer 38"
                        },
                        new
                        {
                            ClientId = 39,
                            Name = "Customer 39"
                        },
                        new
                        {
                            ClientId = 40,
                            Name = "Customer 40"
                        },
                        new
                        {
                            ClientId = 41,
                            Name = "Customer 41"
                        },
                        new
                        {
                            ClientId = 42,
                            Name = "Customer 42"
                        },
                        new
                        {
                            ClientId = 43,
                            Name = "Customer 43"
                        },
                        new
                        {
                            ClientId = 44,
                            Name = "Customer 44"
                        },
                        new
                        {
                            ClientId = 45,
                            Name = "Customer 45"
                        },
                        new
                        {
                            ClientId = 46,
                            Name = "Customer 46"
                        },
                        new
                        {
                            ClientId = 47,
                            Name = "Customer 47"
                        },
                        new
                        {
                            ClientId = 48,
                            Name = "Customer 48"
                        },
                        new
                        {
                            ClientId = 49,
                            Name = "Customer 49"
                        },
                        new
                        {
                            ClientId = 50,
                            Name = "Customer 50"
                        },
                        new
                        {
                            ClientId = 51,
                            Name = "Customer 51"
                        },
                        new
                        {
                            ClientId = 52,
                            Name = "Customer 52"
                        },
                        new
                        {
                            ClientId = 53,
                            Name = "Customer 53"
                        },
                        new
                        {
                            ClientId = 54,
                            Name = "Customer 54"
                        },
                        new
                        {
                            ClientId = 55,
                            Name = "Customer 55"
                        },
                        new
                        {
                            ClientId = 56,
                            Name = "Customer 56"
                        },
                        new
                        {
                            ClientId = 57,
                            Name = "Customer 57"
                        },
                        new
                        {
                            ClientId = 58,
                            Name = "Customer 58"
                        },
                        new
                        {
                            ClientId = 59,
                            Name = "Customer 59"
                        },
                        new
                        {
                            ClientId = 60,
                            Name = "Customer 60"
                        },
                        new
                        {
                            ClientId = 61,
                            Name = "Customer 61"
                        },
                        new
                        {
                            ClientId = 62,
                            Name = "Customer 62"
                        },
                        new
                        {
                            ClientId = 63,
                            Name = "Customer 63"
                        },
                        new
                        {
                            ClientId = 64,
                            Name = "Customer 64"
                        },
                        new
                        {
                            ClientId = 65,
                            Name = "Customer 65"
                        },
                        new
                        {
                            ClientId = 66,
                            Name = "Customer 66"
                        },
                        new
                        {
                            ClientId = 67,
                            Name = "Customer 67"
                        },
                        new
                        {
                            ClientId = 68,
                            Name = "Customer 68"
                        },
                        new
                        {
                            ClientId = 69,
                            Name = "Customer 69"
                        },
                        new
                        {
                            ClientId = 70,
                            Name = "Customer 70"
                        },
                        new
                        {
                            ClientId = 71,
                            Name = "Customer 71"
                        },
                        new
                        {
                            ClientId = 72,
                            Name = "Customer 72"
                        },
                        new
                        {
                            ClientId = 73,
                            Name = "Customer 73"
                        },
                        new
                        {
                            ClientId = 74,
                            Name = "Customer 74"
                        },
                        new
                        {
                            ClientId = 75,
                            Name = "Customer 75"
                        },
                        new
                        {
                            ClientId = 76,
                            Name = "Customer 76"
                        },
                        new
                        {
                            ClientId = 77,
                            Name = "Customer 77"
                        },
                        new
                        {
                            ClientId = 78,
                            Name = "Customer 78"
                        },
                        new
                        {
                            ClientId = 79,
                            Name = "Customer 79"
                        },
                        new
                        {
                            ClientId = 80,
                            Name = "Customer 80"
                        },
                        new
                        {
                            ClientId = 81,
                            Name = "Customer 81"
                        },
                        new
                        {
                            ClientId = 82,
                            Name = "Customer 82"
                        },
                        new
                        {
                            ClientId = 83,
                            Name = "Customer 83"
                        },
                        new
                        {
                            ClientId = 84,
                            Name = "Customer 84"
                        },
                        new
                        {
                            ClientId = 85,
                            Name = "Customer 85"
                        },
                        new
                        {
                            ClientId = 86,
                            Name = "Customer 86"
                        },
                        new
                        {
                            ClientId = 87,
                            Name = "Customer 87"
                        },
                        new
                        {
                            ClientId = 88,
                            Name = "Customer 88"
                        },
                        new
                        {
                            ClientId = 89,
                            Name = "Customer 89"
                        },
                        new
                        {
                            ClientId = 90,
                            Name = "Customer 90"
                        },
                        new
                        {
                            ClientId = 91,
                            Name = "Customer 91"
                        },
                        new
                        {
                            ClientId = 92,
                            Name = "Customer 92"
                        },
                        new
                        {
                            ClientId = 93,
                            Name = "Customer 93"
                        },
                        new
                        {
                            ClientId = 94,
                            Name = "Customer 94"
                        },
                        new
                        {
                            ClientId = 95,
                            Name = "Customer 95"
                        },
                        new
                        {
                            ClientId = 96,
                            Name = "Customer 96"
                        },
                        new
                        {
                            ClientId = 97,
                            Name = "Customer 97"
                        },
                        new
                        {
                            ClientId = 98,
                            Name = "Customer 98"
                        },
                        new
                        {
                            ClientId = 99,
                            Name = "Customer 99"
                        },
                        new
                        {
                            ClientId = 100,
                            Name = "Customer 100"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
